window.QUESTIONS = [
{"ticket":22,"topic":"Finanční analýza","term":"finanční analýza","definition":"Proces hodnocení finanční situace a hospodaření podniku pomocí údajů z účetních výkazů a dalších zdrojů."},
{"ticket":22,"topic":"Finanční analýza","term":"likvidita","definition":"Schopnost podniku včas hradit své krátkodobé závazky."},
{"ticket":22,"topic":"Finanční analýza","term":"rentabilita","definition":"Schopnost podniku vytvářet zisk ve vztahu k vloženému kapitálu, majetku nebo tržbám."},
{"ticket":22,"topic":"Finanční analýza","term":"zadluženost","definition":"Míra, v jaké podnik používá k financování svého majetku cizí zdroje."},
{"ticket":22,"topic":"Finanční analýza","term":"ukazatele aktivity","definition":"Ukazatele, které hodnotí, jak efektivně podnik využívá svůj majetek, například pomocí obratu zásob nebo pohledávek."},
{"ticket":22,"topic":"Finanční analýza","term":"čistý pracovní kapitál","definition":"Rozdíl mezi oběžnými aktivy a krátkodobými závazky. Ukazuje krátkodobou finanční stabilitu podniku."},
{"ticket":23,"topic":"Bod zvratu","term":"fixní náklady","definition":"Náklady, které se v určitém období nemění se změnou objemu výroby, například nájemné."},
{"ticket":23,"topic":"Bod zvratu","term":"variabilní náklady","definition":"Náklady, jejichž celková výše se mění podle objemu výroby nebo prodeje."},
{"ticket":23,"topic":"Bod zvratu","term":"bod zvratu","definition":"Takový objem výroby nebo prodeje, při kterém se celkové výnosy rovnají celkovým nákladům a podnik nevytváří zisk ani ztrátu."},
{"ticket":23,"topic":"Bod zvratu","term":"příspěvek na úhradu","definition":"Rozdíl mezi prodejní cenou produktu a jeho variabilními náklady. Slouží k úhradě fixních nákladů a následně k tvorbě zisku."},
{"ticket":23,"topic":"Bod zvratu","term":"bezpečnostní marže","definition":"Rozdíl mezi skutečným nebo plánovaným objemem prodeje a bodem zvratu. Ukazuje, o kolik může prodej klesnout, než se podnik dostane do ztráty."},
{"ticket":24,"topic":"Manažerské účetnictví a kalkulace","term":"manažerské účetnictví","definition":"Systém interních informací, který pomáhá vedení podniku při plánování, rozhodování a kontrole."},
{"ticket":24,"topic":"Manažerské účetnictví a kalkulace","term":"přímé náklady","definition":"Náklady, které lze přímo přiřadit ke konkrétnímu výrobku, službě nebo zakázce."},
{"ticket":24,"topic":"Manažerské účetnictví a kalkulace","term":"nepřímé náklady","definition":"Náklady, které nelze přímo přiřadit jednomu konkrétnímu výkonu a musí se mezi jednotlivé výkony rozdělit."},
{"ticket":24,"topic":"Manažerské účetnictví a kalkulace","term":"režijní náklady","definition":"Nepřímé náklady související s provozem, správou, výrobou nebo prodejem podniku."},
{"ticket":24,"topic":"Manažerské účetnictví a kalkulace","term":"kalkulace nákladů","definition":"Proces stanovení nákladů na konkrétní výrobek, službu, zakázku nebo jiný výkon."},
{"ticket":24,"topic":"Manažerské účetnictví a kalkulace","term":"kalkulační jednice","definition":"Přesně vymezená jednotka výkonu, pro kterou se náklady stanovují, například jeden výrobek, jedna hodina práce nebo jedna zakázka."},
{"ticket":25,"topic":"Finanční systém a finanční trh","term":"finanční systém","definition":"Soubor finančních institucí, trhů, nástrojů a pravidel, které umožňují přesun peněz mezi subjekty s přebytkem a nedostatkem finančních prostředků."},
{"ticket":25,"topic":"Finanční systém a finanční trh","term":"finanční trh","definition":"Místo nebo systém, ve kterém se setkává nabídka a poptávka po finančních prostředcích a finančních nástrojích."},
{"ticket":25,"topic":"Finanční systém a finanční trh","term":"peněžní trh","definition":"Část finančního trhu zaměřená na krátkodobé finanční prostředky a nástroje se splatností zpravidla do jednoho roku."},
{"ticket":25,"topic":"Finanční systém a finanční trh","term":"kapitálový trh","definition":"Část finančního trhu, na které se získávají a obchodují dlouhodobé finanční prostředky, například akcie a dlouhodobé dluhopisy."},
{"ticket":25,"topic":"Finanční systém a finanční trh","term":"primární trh","definition":"Trh, na kterém jsou nové cenné papíry poprvé vydávány a prodávány investorům."},
{"ticket":25,"topic":"Finanční systém a finanční trh","term":"sekundární trh","definition":"Trh, na kterém investoři obchodují s již dříve vydanými cennými papíry."},
{"ticket":26,"topic":"Zdroje financování podniku","term":"vlastní zdroje financování","definition":"Finanční prostředky, které pocházejí od vlastníků nebo z vlastní činnosti podniku a podnik je nemusí vracet věřiteli."},
{"ticket":26,"topic":"Zdroje financování podniku","term":"cizí zdroje financování","definition":"Prostředky získané od věřitelů, které musí podnik za stanovených podmínek vrátit."},
{"ticket":26,"topic":"Zdroje financování podniku","term":"interní financování","definition":"Financování z prostředků vytvořených uvnitř podniku, například ze zisku nebo z odpisů."},
{"ticket":26,"topic":"Zdroje financování podniku","term":"externí financování","definition":"Financování získané z vnějších zdrojů, například od vlastníků, bank nebo investorů."},
{"ticket":26,"topic":"Zdroje financování podniku","term":"bankovní úvěr","definition":"Peněžní prostředky poskytnuté bankou, které podnik splácí společně s úrokem."},
{"ticket":26,"topic":"Zdroje financování podniku","term":"leasing","definition":"Způsob financování, při kterém podnik používá majetek za pravidelné platby, aniž by ho musel okamžitě koupit."},
{"ticket":26,"topic":"Zdroje financování podniku","term":"factoring","definition":"Financování, při kterém podnik postupuje své krátkodobé pohledávky specializované společnosti a získává peníze dříve, než zaplatí zákazník."},
{"ticket":27,"topic":"Kapitálová struktura","term":"kapitálová struktura","definition":"Poměr vlastních a cizích zdrojů, kterými podnik financuje svůj majetek a činnost."},
{"ticket":27,"topic":"Kapitálová struktura","term":"náklady kapitálu","definition":"Cena, kterou podnik platí za používání vlastního nebo cizího kapitálu."},
{"ticket":27,"topic":"Kapitálová struktura","term":"WACC","definition":"Vážené průměrné náklady kapitálu, které vyjadřují průměrnou cenu všech zdrojů financování podniku."},
{"ticket":27,"topic":"Kapitálová struktura","term":"finanční páka","definition":"Vliv použití cizího kapitálu na výnosnost vlastního kapitálu. Dluh může výnosnost zvýšit, ale zároveň zvyšuje finanční riziko."},
{"ticket":27,"topic":"Kapitálová struktura","term":"optimální kapitálová struktura","definition":"Takový poměr vlastního a cizího kapitálu, který udržuje náklady financování a finanční riziko na přijatelné úrovni."},
{"ticket":28,"topic":"Řízení oběžného majetku","term":"řízení pracovního kapitálu","definition":"Řízení krátkodobého majetku a krátkodobých závazků tak, aby měl podnik dostatek prostředků pro běžný provoz."},
{"ticket":28,"topic":"Řízení oběžného majetku","term":"řízení zásob","definition":"Rozhodování o množství, termínech a způsobu doplňování zásob s cílem zabránit jejich nedostatku i nadměrnému množství."},
{"ticket":28,"topic":"Řízení oběžného majetku","term":"řízení pohledávek","definition":"Stanovení platebních podmínek, sledování splatnosti a vymáhání pohledávek tak, aby zákazníci platili včas."},
{"ticket":28,"topic":"Řízení oběžného majetku","term":"řízení peněžních prostředků","definition":"Plánování a kontrola příjmů a výdajů tak, aby byl podnik schopen průběžně plnit své platební povinnosti."},
{"ticket":28,"topic":"Řízení oběžného majetku","term":"peněžní cyklus","definition":"Doba mezi zaplacením vstupů dodavatelům a přijetím peněz od zákazníků za prodané výrobky nebo služby."},
{"ticket":29,"topic":"Investiční rozhodování","term":"investiční projekt","definition":"Plán dlouhodobého použití finančních prostředků, od kterého podnik očekává budoucí ekonomické přínosy."},
{"ticket":29,"topic":"Investiční rozhodování","term":"peněžní tok investice","definition":"Očekávané příjmy a výdaje, které vzniknou v souvislosti s investičním projektem."},
{"ticket":29,"topic":"Investiční rozhodování","term":"časová hodnota peněz","definition":"Princip, podle kterého mají peníze dnes vyšší hodnotu než stejná částka získaná v budoucnosti."},
{"ticket":29,"topic":"Investiční rozhodování","term":"diskontní sazba","definition":"Procentní míra používaná k přepočtu budoucích peněžních toků na jejich současnou hodnotu."},
{"ticket":29,"topic":"Investiční rozhodování","term":"čistá současná hodnota","definition":"Rozdíl mezi současnou hodnotou budoucích peněžních příjmů a počátečními výdaji na investici."},
{"ticket":29,"topic":"Investiční rozhodování","term":"vnitřní výnosové procento","definition":"Taková diskontní sazba, při které je čistá současná hodnota investice rovna nule."},
{"ticket":29,"topic":"Investiční rozhodování","term":"doba návratnosti","definition":"Doba, za kterou se počáteční investiční výdaj vrátí prostřednictvím peněžních příjmů z projektu."},
{"ticket":30,"topic":"Oceňování podniku","term":"oceňování podniku","definition":"Proces stanovení ekonomické hodnoty podniku k určitému účelu a určitému datu."},
{"ticket":30,"topic":"Oceňování podniku","term":"tržní hodnota podniku","definition":"Odhadovaná cena, za kterou by mohl být podnik prodán mezi informovaným kupujícím a prodávajícím."},
{"ticket":30,"topic":"Oceňování podniku","term":"majetkové ocenění","definition":"Ocenění podniku založené především na hodnotě jeho jednotlivých složek majetku po odečtení závazků."},
{"ticket":30,"topic":"Oceňování podniku","term":"výnosové ocenění","definition":"Ocenění založené na očekávaných budoucích výnosech nebo peněžních tocích podniku."},
{"ticket":30,"topic":"Oceňování podniku","term":"metoda DCF","definition":"Výnosová metoda, při které se budoucí volné peněžní toky převádějí pomocí diskontní sazby na současnou hodnotu."},
{"ticket":30,"topic":"Oceňování podniku","term":"terminální hodnota","definition":"Hodnota očekávaných výnosů podniku po skončení období, pro které byly vytvořeny podrobné finanční prognózy."}
];